---


- name: Block Incoming Connections from IP 
  when: network_operation == "blockFromIp"
  shell : iptables -I INPUT 1 -s {{ item }} -j DROP
  with_items:
   "{{ ipAddress }}"
  notify : ListInputConnections


- name: Undo Block Connections from IP
  when : network_operation == "undo_blockFromIp"
  shell: iptables -D INPUT -s {{ item }} -j  DROP
  with_items:
   "{{ ipAddress }}"
  notify : ListInputConnections

- name: Block Outgoing Connections to IP
  when: network_operation == "blockToIp"
  shell : iptables -I OUTPUT 1 -d {{ item }} -j DROP
  with_items:
   "{{ ipAddress }}"


- name: Undo Block Connections to IP
  when : network_operation == "undo_blockToIp"
  shell: iptables -D OUTPUT -d {{ item }} -j  DROP
  with_items:
   "{{ ipAddress }}"



- name: Block All Incoming Connections
  when : network_operation == "block_all_incoming"
  shell: "{{ item }}"
  with_items:
   - iptables -I INPUT 1 -p tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
   - iptables -I OUTPUT 2 -p tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
   - iptables -I INPUT 3  -j DROP
 

- name : Undo Block All Incoming Connections
  when : network_operation == "undo_block_all_incoming"
  shell: "{{ item }}"
  with_items:
   - iptables -D INPUT  -j DROP
   - iptables -D INPUT -p tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
   - iptables -D OUTPUT -p tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT


- name : Block All Outgoing Connections
  when : network_operation == "block_all_outgoing"
  shell: "{{ item }}"
  with_items:
   - iptables -I OUTPUT 1 -p tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
   - iptables -I INPUT 2 -p tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT
   - iptables -I OUTPUT 3 -j DROP


- name : Undo Block All Outgoing Connections
  when : network_operation == "undo_block_all_outgoing"
  shell: "{{ item }}"
  with_items:
   - iptables -D INPUT  -j DROP
   - iptables -D INPUT -p tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
   - iptables -D OUTPUT -p tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT



- name: Block Communication based on domain name
  when: network_operation == "block_by_domainName"
  lineinfile: "dest=/etc/hosts insertafter=EOF line='127.0.0.1 {{item}}'" 
  with_items:
   "{{domainName}}"


- name: Undo Block Communication based on domain name
  when: network_operation == "undo_block_by_domainName"
  lineinfile: "dest=/etc/hosts state=absent line='127.0.0.1 {{item}}'"
  with_items:
   "{{domainName}}"

 


- name: Restart the network Interface {{ interface_name }} within time interval of {{ timeInterval }}
  service:  name = netwokr state = restarte args =  {{interface_name}} sleep = {{ timeInterval }}
  when : network_operation == "restart_network_interface"

